# Generated by Django 4.0.2 on 2022-10-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_country', to='JailuApp.country')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_type', models.CharField(max_length=50)),
                ('operation_summary', models.CharField(max_length=100)),
                ('full_description', models.CharField(max_length=500)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'system_log',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_photo', models.CharField(blank=True, max_length=150, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_email', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_setting_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_setting_modified_by', to='JailuApp.useraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_setting_user', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='JailuApp.usergroup'),
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=200)),
                ('add', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('list', models.BooleanField(default=False)),
                ('view', models.BooleanField(default=False)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='JailuApp.usergroup')),
            ],
            options={
                'db_table': 'group_permission',
            },
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_type_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_type_modified_by', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'department_type',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSupervisor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_supervisor_department', to='JailuApp.department')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_supervisor_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_supervisor_modified_by', to='JailuApp.useraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_supervisor_user', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'department_supervisor',
            },
        ),
        migrations.CreateModel(
            name='DepartmentEmployee',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_employee_department', to='JailuApp.department')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_employee_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_employee_modified_by', to='JailuApp.useraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_employee_user', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'department_employee',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_department_type', to='JailuApp.departmenttype'),
        ),
        migrations.AddField(
            model_name='department',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_entered_by', to='JailuApp.useraccount'),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_modified_by', to='JailuApp.useraccount'),
        ),
        migrations.AddField(
            model_name='country',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_entered_by', to='JailuApp.useraccount'),
        ),
        migrations.AddField(
            model_name='country',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_modified_by', to='JailuApp.useraccount'),
        ),
    ]
